/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/signals/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Signals */
        get: operations["read_signals_api_v1_signals__get"];
        put?: never;
        /** Create Signal */
        post: operations["create_signal_api_v1_signals__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/signals/{signal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Signal */
        get: operations["read_signal_api_v1_signals__signal_id__get"];
        /** Update Signal */
        put: operations["update_signal_api_v1_signals__signal_id__put"];
        post?: never;
        /** Delete Signal */
        delete: operations["delete_signal_api_v1_signals__signal_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ObjectType
         * @enum {string}
         */
        ObjectType: "Change Event" | "Trend Alert";
        /** SignalCreate */
        SignalCreate: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            object_type: components["schemas"]["ObjectType"];
            type: components["schemas"]["SignalType"];
            temporal: components["schemas"]["TemporalStatus"];
            /** Normalized Status */
            normalized_status: string;
            /** Sop */
            sop: string;
            /** Certainty */
            certainty: number;
            /** Magnitude */
            magnitude: number;
            /**
             * Riskrag
             * @default Amber
             * @enum {unknown}
             */
            riskRag: "Red" | "Amber" | "Green";
            /** Readinessscore */
            readinessScore?: number | null;
            /** Description */
            description?: string | null;
            /** Source */
            source?: string | null;
            /** Sources */
            sources?: {
                [key: string]: string;
            }[] | null;
            /** Tags */
            tags?: string[] | null;
            /** Obligations */
            obligations?: string[] | null;
            /** Signal Metadata */
            signal_metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** SignalInDB */
        SignalInDB: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            object_type: components["schemas"]["ObjectType"];
            type: components["schemas"]["SignalType"];
            temporal: components["schemas"]["TemporalStatus"];
            /** Normalized Status */
            normalized_status: string;
            /** Sop */
            sop: string;
            /** Certainty */
            certainty: number;
            /** Magnitude */
            magnitude: number;
            /**
             * Riskrag
             * @default Amber
             * @enum {unknown}
             */
            riskRag: "Red" | "Amber" | "Green";
            /** Readinessscore */
            readinessScore?: number | null;
            /** Description */
            description?: string | null;
            /** Source */
            source?: string | null;
            /** Sources */
            sources?: {
                [key: string]: string;
            }[] | null;
            /** Tags */
            tags?: string[] | null;
            /** Obligations */
            obligations?: string[] | null;
            /** Signal Metadata */
            signal_metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SignalType
         * @enum {string}
         */
        SignalType: "Amendment" | "Judgment" | "Ruling" | "Opinion";
        /** SignalUpdate */
        SignalUpdate: {
            /** Title */
            title?: string | null;
            object_type?: components["schemas"]["ObjectType"] | null;
            type?: components["schemas"]["SignalType"] | null;
            temporal?: components["schemas"]["TemporalStatus"] | null;
            /** Normalized Status */
            normalized_status?: string | null;
            /** Sop */
            sop?: string | null;
            /** Certainty */
            certainty?: number | null;
            /** Magnitude */
            magnitude?: number | null;
            /**
             * Riskrag
             * @enum {unknown}
             */
            riskRag?: "Red" | "Amber" | "Green";
            /** Readinessscore */
            readinessScore?: number | null;
            /** Description */
            description?: string | null;
            /** Source */
            source?: string | null;
            /** Sources */
            sources?: {
                [key: string]: string;
            }[] | null;
            /** Tags */
            tags?: string[] | null;
            /** Obligations */
            obligations?: string[] | null;
            /** Signal Metadata */
            signal_metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * TemporalStatus
         * @enum {string}
         */
        TemporalStatus: "Pending" | "Trending" | "Ending";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_signals_api_v1_signals__get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                /** @description Filter by object type */
                object_type?: string[] | null;
                /** @description Filter by signal type */
                signal_type?: string[] | null;
                /** @description Filter by temporal status */
                temporal?: string[] | null;
                /** @description Filter by tags */
                tags?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalInDB"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_signal_api_v1_signals__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignalCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalInDB"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_signal_api_v1_signals__signal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalInDB"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_signal_api_v1_signals__signal_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignalUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalInDB"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_signal_api_v1_signals__signal_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
