/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new user
         * @description Create a new user.
         */
        post: operations["create_user_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login a user
         * @description Login a user
         */
        post: operations["login_user_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organisations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Org */
        post: operations["create_org_organisations__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organisations/{organisation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Organisation With Users */
        get: operations["get_organisation_with_users_organisations__organisation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regulatory-programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Regulatory Programs
         * @description List all regulatory programs.
         */
        get: operations["list_regulatory_programs_regulatory_programs_get"];
        put?: never;
        /**
         * Create Regulatory Program
         * @description Create a new regulatory program.
         */
        post: operations["create_regulatory_program_regulatory_programs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/regulatory-programs/{program_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Regulatory Program */
        get: operations["get_regulatory_program_regulatory_programs__program_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint to verify server status.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthCheckResponse
         * @description Response model for health check endpoint.
         */
        HealthCheckResponse: {
            /** Status */
            status: string;
        };
        /** OrganisationCreationRequest */
        OrganisationCreationRequest: {
            /** Name */
            name: string;
        };
        /** OrganisationResponse */
        OrganisationResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Lastupdatedat
             * Format: date-time
             */
            lastUpdatedAt: string;
        };
        /**
         * OrganisationRole
         * @enum {string}
         */
        OrganisationRole: "OWNER" | "ADMIN" | "STAFF" | "VIEWER";
        /** OrganisationWithUsersResponse */
        OrganisationWithUsersResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Lastupdatedat
             * Format: date-time
             */
            lastUpdatedAt: string;
            /** Users */
            users: components["schemas"]["UserResponse"][];
        };
        /**
         * RegulatoryProgramCreateRequest
         * @description Request body for creating a regulatory program.
         */
        RegulatoryProgramCreateRequest: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /**
         * RegulatoryProgramResponse
         * @description Response schema returned by the API.
         */
        RegulatoryProgramResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
        };
        /**
         * UserLoginRequest
         * @description Request model for logging in a user.
         */
        UserLoginRequest: {
            /**
             * Email
             * Format: email
             * @description Email address of the user logging in.
             */
            email: string;
            /**
             * Password
             * @description Password of the user logging in.
             */
            password: string;
        };
        /**
         * UserLoginResponse
         * @description Request model for logging in a user.
         */
        UserLoginResponse: {
            /**
             * Access Token
             * @description JWT token response.
             */
            access_token: string;
            /**
             * Token Type
             * @description Token type, e.g. Bearer
             * @default bearer
             */
            token_type: string;
        };
        /** UserMeResponse */
        UserMeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Createdat */
            createdAt: string;
            organisation: components["schemas"]["OrganisationResponse"] | null;
            role: components["schemas"]["OrganisationRole"] | null;
        };
        /**
         * UserRegistrationRequest
         * @description Request model for creating a new user.
         */
        UserRegistrationRequest: {
            /**
             * Email
             * Format: email
             * @description Email address of the person being creating the account.
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * UserRegistrationResponse
         * @description Response model for a create user request.
         */
        UserRegistrationResponse: {
            /**
             * Id
             * Format: uuid
             * @description Unique identifier for the user.
             */
            id: string;
            /**
             * Email
             * @description Email address of the person being creating the account.
             */
            email: string;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_user_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegistrationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRegistrationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_user_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserLoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMeResponse"];
                };
            };
        };
    };
    create_org_organisations__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganisationCreationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganisationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_organisation_with_users_organisations__organisation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organisation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganisationWithUsersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_regulatory_programs_regulatory_programs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegulatoryProgramResponse"][];
                };
            };
        };
    };
    create_regulatory_program_regulatory_programs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegulatoryProgramCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegulatoryProgramResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_regulatory_program_regulatory_programs__program_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                program_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegulatoryProgramResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheckResponse"];
                };
            };
        };
    };
}
